kind: pipeline
name: default

steps:
- name: setup
  image: abakus/lego-testbase
  when:
    event: push
  environment:
    LANG: C.UTF-8
  commands:
    - make ci_settings

- name: missing-migrations
  image: abakus/lego-testbase
  when:
    event: push
  environment:
    LANG: C.UTF-8
    DATABASE: database
    CACHE: cache
  depends_on: [ setup ]
  commands:
    - tox -e missing-migrations

- name: tests
  image: abakus/lego-testbase
  when:
    event: push
  environment:
    LANG: C.UTF-8
    DATABASE: database
    CACHE: cache
  depends_on: [ setup ]
  commands:
    - tox -e tests

- name: isort
  image: abakus/lego-testbase
  when:
    event: push
  environment:
    LANG: C.UTF-8
  depends_on: [ setup ]
  commands:
    - tox -e isort

- name: flake8
  image: abakus/lego-testbase
  when:
    event: push
  environment:
    LANG: C.UTF-8
  depends_on: [ setup ]
  commands:
    - tox -e flake8

- name: black
  image: abakus/lego-testbase
  when:
    event: push
  environment:
    LANG: C.UTF-8
  depends_on: [ setup ]
  commands:
    - tox -e black

- name: docs
  image: abakus/lego-testbase
  when:
    event: push
  environment:
    LANG: C.UTF-8
  depends_on: [ setup ]
  commands:
    - tox -e docs

- name: coverage
  image: abakus/lego-testbase
  when:
    event: push
  environment:
    LANG: C.UTF-8
  depends_on: [ tests ]
  commands:
    - tox -e coverage

- name: docker
  image: plugins/docker
  when:
    branch:
      - prod
    status: success
    event: push
  registry: https://registry.abakus.no
  repo: registry.abakus.no/webkom/lego
  secrets: [ docker_username, docker_password ]
  depends_on: [ coverage, docs, black, flake8, isort, tests, missing-migrations ]
  tags:
    - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
  build_args:
    - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

services:
- name: database
  image: postgres:9.5
  environment:
    POSTGRES_USER: lego
  ports:
    - 5432
- name: cache
  image: redis:latest
  ports:
    - 6379
